In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('ENFR 2018 - Base usuario.txt', sep='|')

## Analisis de columnas

In [3]:
df.columns

Index(['id', 'cod_provincia', 'region', 'tamanio_aglomerado', 'aglomerado',
       'localidades_150', 'submuestra', 'bhcv01', 'bhcv02', 'bhcv03',
       ...
       'glucemia_elevada', 'prevalencia_glucemia_elevada_combinada',
       'findrisc', 'bimq06', 'bimq06_01', 'colesterol_elevado',
       'prevalencia_colesterol_combinada', 'wf1p', 'wf2p', 'wf3p'],
      dtype='str', length=287)

- **id, cod_provincia, region, tamanio_aglomerado, aglomerado:** Identifican dónde vive la persona

- **bhcv01–bhcv11:** Bloque de características de la vivienda.

- **bhho01–bhho03:** Características del hogar.

- **cant_componentes, miembros_18, tipo_hogar:** Composición del hogar.

- **bhih01, rango_ingreso, quintil_uc:** Ingresos y nivel económico del hogar.

- **bhch...:** Datos sociodemográficos, como edad, educación y cobertura de salud.

- **bisl..., bisg...:** Variables de salud y otros aspectos sociodemográficos.

- **biaf...:** Actividad física y sus barreras.

- **bita...:** Tabaco y aspectos relacionados con su consumo.

- **biha...:** Hipertensión arterial.

- **bipc..., imc, imc_categorias:** Peso, talla e índice de masa corporal.

- **bial...:** Alimentación y consumo de frutas y verduras.

- **bico...:**  Colesterol.

- **bica..., consumo_regular_riesgo:** Consumo de alcohol y patrones de riesgo.

- **bidi...:** Diabetes.

- **bile..., bipp..., bicc...:** Otros controles de salud, prevención y detección de enfermedades.

- **bima..., bimq...:** Mediciones físicas y bioquímicas de la submuestra.

- **wf1p, wf2p, wf3p:** Variables de ponderación o factores de expansión; hay que consultar el diccionario para distinguirlas.

In [4]:
df["wf1p"]

0        2378
1        3588
2        2740
3         493
4        2016
         ...
29219     203
29220    1042
29221     441
29222     544
29223     220
Name: wf1p, Length: 29224, dtype: int64

In [5]:
df.head()

,id,cod_provincia,region,tamanio_aglomerado,aglomerado,localidades_150,submuestra,bhcv01,bhcv02,bhcv03,...,glucemia_elevada,prevalencia_glucemia_elevada_combinada,findrisc,bimq06,bimq06_01,colesterol_elevado,prevalencia_colesterol_combinada,wf1p,wf2p,wf3p
0,1128639,2,1,1,1,1,1,3,2,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2378,4464,0
1,1709939,2,1,1,1,1,0,1,4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3588,0,0
2,6874130,2,1,1,1,1,0,3,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2740,0,0
3,10319375,2,1,1,1,1,1,3,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,493,0,0
4,11140857,2,1,1,1,1,0,3,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,0,0

## Nulos

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29224 entries, 0 to 29223
Columns: 287 entries, id to wf3p
dtypes: float64(186), int64(101)
memory usage: 64.0 MB

### El dataset tiene 29.224 registros con 287 columnas

In [7]:
porcentaje_nulos = (df.isnull().sum() / len(df)) * 100

columnas_con_nulos = porcentaje_nulos[porcentaje_nulos > 0].sort_values(ascending=False)

df_nulos = pd.DataFrame({'Porcentaje de Nulos (%)': columnas_con_nulos})

df_nulos.head(32)

             Porcentaje de Nulos (%)
bita06_b_99                99.941829
biha06_99                  99.921298
biaf02_99                  99.869970
biha11_99                  99.842595
biaf04_99                  99.811799
bita02_99                  99.562004
bimq05_01                  99.510676
bica03_99                  99.473036
bhch10_99                  99.473036
bhch10_99_j                99.469614
biaf06_99                  99.404599
bita07_99                  99.404599
biha11                     99.209554
bisl03                     99.206132
bhsl03                     99.189023
bial06_99                  99.113742
bial05_99                  99.017930
bhsl05                     98.795511
bisl05                     98.644949
bimq06_01                  98.562825
bial04_99                  98.460170
bial03_99                  98.046126
bhch10_05                  97.998221
bhch10_05_j                97.922940
bhch10_04                  97.614974
bhch10_04_j                97.464413
bipc04_99                  96.540515
bhch10_03                  96.314673
bhch10_03_j                96.287298
bita06_d                   96.229127
biaf07_99                  96.201752
bhsl04                     95.459212

#### Hay columnas con muchos nulos, podemos ver que hay 17 columnas con mas del 99% de nulos